### ISSUE TITLE
Keeps showing “ loading”

### ISSUE THREAD

**Issue by jasb1011** [roramirez/MagicMirror-Module-Template#15]
When I had first downloaded the MM software everything was fine except the underneath the US Holidays calendar it would just say “no upcoming” events instead of showing the us Holidays. The I tried syncing it to my google calendar by putting my iCal public address and now it just shows “loading” underneath. Please help me fix this problem.

**Comment by roramirez** [comment]
Sorry but this project is to create a Module Template.  Maybe can help in the forum https://forum.magicmirror.builders/
